// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lorgus.UI.Models
{
    public partial class AccessLevel
    {
        public AccessLevel()
        {
            User = new HashSet<User>();
        }

        public short AccessLevelId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}