// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lorgus.UI.Models
{
    public partial class User
    {
        public User()
        {
            RequestChangePassword = new HashSet<RequestChangePassword>();
        }

        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public byte[] PasswordSalt { get; set; }
        public byte[] PasswordHash { get; set; }
        public short AccessLevelId { get; set; }

        public virtual AccessLevel AccessLevel { get; set; }
        public virtual ICollection<RequestChangePassword> RequestChangePassword { get; set; }
    }
}